apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-risk-model-deployment
  labels:
    app: credit-risk-model-service
    app.kubernetes.io/name: credit-risk-model-service
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: model-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-risk-model-service
  template:
    metadata:
      labels:
        app: credit-risk-model-service
    spec:
      containers:
        - name: credit-risk-model
          image: credit_risk_model_service:0.1.0
          ports:
          - containerPort: 80
            protocol: TCP
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /api/health
              port: 8000
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /api/health/ready
              port: 8000
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5
            successThreshold: 1
          startupProbe:
            httpGet:
              scheme: HTTP
              path: /api/health/startup
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 5
            successThreshold: 1
          resources:
            requests:
              cpu: "100m"
              memory: "250Mi"
            limits:
              cpu: "200m"
              memory: "250Mi"
          env:
            - name: REST_CONFIG
              value: ./configuration/kubernetes_rest_config.yaml
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: APP_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
          volumeMounts:
            - name: config-volume
              mountPath: /service/configuration
      volumes:
        - name: config-volume
          configMap:
            name: model-service-configuration
            items:
              - key: kubernetes_rest_config.yaml
                path: kubernetes_rest_config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: credit-risk-model-service
  labels:
    app.kubernetes.io/name: credit-risk-model-service
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: model-service
spec:
  type: NodePort
  selector:
    app: credit-risk-model-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000